modules loaded

Currently Loaded Modules:
  1) build/gcc-7.2.0   2) languages/anaconda2/5.0.1   3) tools/git/2.18.0

2018-09-25 15:25:20,969 - isca - INFO - Writing path_names to '/mnt/storage/home/dm16883/Exo-planets/Model_runs/codebase/_mnt_storage_home_dm16883_Exo-planets_Isca/build/isca/path_names'
2018-09-25 15:25:20,985 - isca - INFO - Running compiler
2018-09-25 15:25:21,165 - isca - INFO - loadmodules for Bluecrystal 4 machines
2018-09-25 15:25:21,429 - isca - INFO - Currently Loaded Modules:
2018-09-25 15:25:21,430 - isca - INFO - 1) GCCcore/5.4.0                     6) vtune/2017.1.132-GCC-5.4.0-2.26
2018-09-25 15:25:21,430 - isca - INFO - 2) binutils/2.26-GCCcore-5.4.0       7) imkl/2017.1.132-GCC-5.4.0-2.26
2018-09-25 15:25:21,430 - isca - INFO - 3) icc/2017.1.132-GCC-5.4.0-2.26     8) languages/intel/2017.01
2018-09-25 15:25:21,430 - isca - INFO - 4) ifort/2017.1.132-GCC-5.4.0-2.26   9) libs/hdf5/1.10.1.MPI
2018-09-25 15:25:21,430 - isca - INFO - 5) impi/2017.1.132-GCC-5.4.0-2.26   10) libs/netcdf/4.4.1.1.MPI
2018-09-25 15:25:21,458 - isca - INFO - /mnt/storage/home/dm16883/Exo-planets/Model_runs/codebase/_mnt_storage_home_dm16883_Exo-planets_Isca/build/isca/path_names
2018-09-25 15:25:26,662 - isca - INFO - ................................................................................................................................................................................................... Makefile is ready.
2018-09-25 15:25:26,873 - isca - INFO - make: Nothing to be done for `all'.
2018-09-25 15:25:27,049 - isca - INFO - make: `isca.x' is up to date.
2018-09-25 15:25:27,055 - isca - INFO - Compilation complete.
2018-09-25 15:25:27,056 - isca - DEBUG - Making directory '/mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2'
2018-09-25 15:25:27,075 - isca - WARNING - Tried to remove run directory but it doesnt exist
2018-09-25 15:25:27,083 - isca - INFO - Emptied run directory '/mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run'
2018-09-25 15:25:27,099 - isca - INFO - Emptied run directory '/mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run'
2018-09-25 15:25:27,476 - isca - INFO - Writing namelist to '/mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run/input.nml'
2018-09-25 15:25:27,477 - isca - INFO - Writing field_table to '/mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run/field_table'
2018-09-25 15:25:27,488 - isca - INFO - Writing diag_table to '/mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run/diag_table'
2018-09-25 15:25:27,488 - isca - INFO - Running without restart file
2018-09-25 15:25:27,492 - isca - INFO - Beginning run 1
2018-09-25 15:25:27,496 - isca - INFO - process running as 7886
2018-09-25 15:25:27,611 - isca - DEBUG - loadmodules for Bluecrystal 4 machines
2018-09-25 15:25:27,774 - isca - DEBUG - 
2018-09-25 15:25:27,774 - isca - DEBUG - Currently Loaded Modules:
2018-09-25 15:25:27,774 - isca - DEBUG - 1) GCCcore/5.4.0                     6) vtune/2017.1.132-GCC-5.4.0-2.26
2018-09-25 15:25:27,774 - isca - DEBUG - 2) binutils/2.26-GCCcore-5.4.0       7) imkl/2017.1.132-GCC-5.4.0-2.26
2018-09-25 15:25:27,774 - isca - DEBUG - 3) icc/2017.1.132-GCC-5.4.0-2.26     8) languages/intel/2017.01
2018-09-25 15:25:27,774 - isca - DEBUG - 4) ifort/2017.1.132-GCC-5.4.0-2.26   9) libs/hdf5/1.10.1.MPI
2018-09-25 15:25:27,774 - isca - DEBUG - 5) impi/2017.1.132-GCC-5.4.0-2.26   10) libs/netcdf/4.4.1.1.MPI
2018-09-25 15:25:27,774 - isca - DEBUG - 
2018-09-25 15:25:29,268 - isca - DEBUG - NOTE from PE    0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to    32768.
2018-09-25 15:25:29,268 - isca - DEBUG - &MPP_IO_NML
2018-09-25 15:25:29,268 - isca - DEBUG - HEADER_BUFFER_VAL       =       16384,
2018-09-25 15:25:29,268 - isca - DEBUG - GLOBAL_FIELD_ON_ROOT_PE = T,
2018-09-25 15:25:29,269 - isca - DEBUG - IO_CLOCKS_ON    = F,
2018-09-25 15:25:29,270 - isca - DEBUG - SHUFFLE =           0,
2018-09-25 15:25:29,270 - isca - DEBUG - DEFLATE_LEVEL   =          -1
2018-09-25 15:25:29,270 - isca - DEBUG - /
2018-09-25 15:25:29,270 - isca - DEBUG - NOTE from PE    0: MPP_IO_SET_STACK_SIZE: stack size set to     131072.
2018-09-25 15:25:29,273 - isca - DEBUG - NOTE from PE    0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to   600000.
2018-09-25 15:25:29,282 - isca - DEBUG - starting            1  OpenMP threads per MPI-task
2018-09-25 15:25:29,284 - isca - DEBUG - 
2018-09-25 15:25:29,284 - isca - DEBUG - FATAL from PE    2: SPEC_MPP_INIT:Requires num_lat_rows/num_pes=int;num_pes=  12;num_lat_rows=  64
2018-09-25 15:25:29,284 - isca - DEBUG - 
2018-09-25 15:25:29,284 - isca - DEBUG - 
2018-09-25 15:25:29,284 - isca - DEBUG - FATAL from PE    6: SPEC_MPP_INIT:Requires num_lat_rows/num_pes=int;num_pes=  12;num_lat_rows=  64
2018-09-25 15:25:29,284 - isca - DEBUG - 
2018-09-25 15:25:29,284 - isca - DEBUG - 
2018-09-25 15:25:29,284 - isca - DEBUG - FATAL from PE    1: SPEC_MPP_INIT:Requires num_lat_rows/num_pes=int;num_pes=  12;num_lat_rows=  64
2018-09-25 15:25:29,284 - isca - DEBUG - 
2018-09-25 15:25:29,284 - isca - DEBUG - application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
2018-09-25 15:25:29,285 - isca - DEBUG - application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
Exception in thread background thread for pid 7886:
Traceback (most recent call last):
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bash /mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run/run.sh

  STDOUT:


  STDERR:


2018-09-25 15:25:29,340 - isca - ERROR - Run 1 failed. See log for details.
2018-09-25 15:25:29,340 - isca - ERROR - Error: ErrorReturnCode_1('\n\n  RAN: /usr/bin/bash /mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run/run.sh\n\n  STDOUT:\n\n\n  STDERR:\n',)
Traceback (most recent call last):
  File "/mnt/storage/home/dm16883/Exo-planets/Isca/src/extra/python/isca/experiment.py", line 266, in run
    proc.wait()
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/mnt/storage/home/dm16883/.conda/envs/isca_env/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bash /mnt/storage/home/dm16883/Exo-planets/Model_runs/experiment/frierson_test_experiment2/run/run.sh

  STDOUT:


  STDERR:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frierson_test_case_bc-run.py", line 176, in <module>
    exp.run(1, use_restart=False, num_cores=NCORES)
  File "/mnt/storage/home/dm16883/Exo-planets/Isca/src/extra/python/isca/helpers.py", line 22, in _destructive
    return fn(*args, **kwargs)
  File "/mnt/storage/home/dm16883/Exo-planets/Isca/src/extra/python/isca/helpers.py", line 38, in _useworkdir
    return fn(*args, **kwargs)
  File "/mnt/storage/home/dm16883/Exo-planets/Isca/src/extra/python/isca/experiment.py", line 280, in run
    raise FailedRunError()
isca.experiment.FailedRunError

real	0m15.524s
user	0m1.807s
sys	0m0.655s
